@baseUrl = https://secure-shelf-79053.herokuapp.com/api/notes

GET {{baseUrl}}

###

GET {{baseUrl}}/1

###

DELETE {{baseUrl}}/4

###

POST {{baseUrl}}
Content-Type: application/json

{
    "content": "Postman is a good tool for testing REST apis",
    "important": true
}

###
GET http://localhost:3001